healthCheckTimeout: 500
proxy:
  listen: "http://0.0.0.0:10732"
macros:
  "context_size": "${env.LLAMA_ARG_CTX_SIZE}"
  "parallel": "${env.LLAMA_ARG_N_PARALLEL}"
  "models_dir": "${env.HOME}/models"
  "ssl_key": "${env.HOME}/certs/my.key"
  "ssl_cert": "${env.HOME}/certs/my.pem"
models:
  "smollm2":
    proxy: "http://127.0.0.1:${PORT}"
    description: "When should the model be used?"
    cmd: |
      llama-server
      --ctx-size 4096
      --batch-size 2048
      --host 0.0.0.0
      --jinja
      --model ${models_dir}/SmolLM2-135M-Instruct-Q4_K_M.gguf
      --parallel 2
      --port ${PORT}
      --sleep-idle-seconds 600
      --tools all
      --ubatch-size 2048
  "qwen2.5":
    proxy: "http://127.0.0.1:${PORT}"
    description: "When should the model be used?"
    cmd: |
      llama-server
      --ctx-size 4096
      --batch-size 2048
      --host 0.0.0.0
      --jinja
      --model ${models_dir}/Qwen2.5-0.5B-Instruct-Q4_K_M.gguf
      --parallel 2
      --port ${PORT}
      --sleep-idle-seconds 600
      --tools all
      --ubatch-size 2048