ARG VERSION=latest
FROM ghcr.io/jhwohlgemuth/notebook:$VERSION
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/agentic
LABEL org.opencontainers.image.description="CUDA-enabled llama.cpp server for local LLM inference"
LABEL org.opencontainers.image.licenses=MIT
#
# %arguments
#
ARG IMAGE=agentic
ARG USER_NAME=nonroot
ARG HOME="/home/${USER_NAME}"
ARG CONTEXT_SIZE=4096
ARG PORT=1720
ARG MODEL_DIRECTORY="${HOME}/models"
ARG MODEL_NAME="gpt-oss-20b-GGUF"
ARG HF_REPO="ggml-org/${MODEL_NAME}"
#
# %environment
#
# LLM API endpoint (1720 = TKNS)
EXPOSE 1720
ENV CC=gcc-14
ENV CXX=g++-14
ENV CUDAHOSTCXX=g++-14
ENV CUDA_HOME=/usr/local/cuda
ENV PATH="${CUDA_HOME}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}"
ENV LLAMA_ARG_CTX_SIZE="${CONTEXT_SIZE}"
ENV LLAMA_ARG_HF_REPO="${HF_REPO}"
ENV LLAMA_ARG_HOST=0.0.0.0
ENV LLAMA_ARG_MODEL="${MODEL_DIRECTORY}/${MODEL_NAME}"
ENV LLAMA_ARG_MODELS_DIR="${MODEL_DIRECTORY}"
ENV LLAMA_ARG_PORT="${PORT}"
#
# %files
#
COPY --chmod=0755 --chown=${USER_NAME}:${USER_NAME} ./provision/healthcheck /healthcheck
COPY --chmod=0755 --chown=${USER_NAME}:${USER_NAME} ./config/llama.cpp/service/* /etc/services.d/llama.cpp/
COPY --chmod=0755 --chown=${USER_NAME}:${USER_NAME} ./provision/agentic/* /tmp/scripts/
#
# %post
#
USER root
RUN install_cuda_toolkit
USER "${USER_NAME}"
# RUN --mount=type=secret,id=HF_API_TOKEN \
#     && mkdir -p "${MODEL_DIRECTORY}" && chmod 777 "${MODEL_DIRECTORY}" \
#     && curl -LsSf https://hf.co/cli/install.sh | bash \
#     && /tmp/scripts/build_llama_cpp_from_source.sh \
#    && hf download "${HF_REPO}" --local-dir "${MODEL_DIRECTORY}" --token "${HF_API_TOKEN}"
RUN --mount=type=secret,id=HF_API_TOKEN,env=HF_API_TOKEN \
    mkdir -p "${MODEL_DIRECTORY}" && chmod 777 "${MODEL_DIRECTORY}" \
    && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" \
    && brew install --force hf llama.cpp \
    && hf download "${HF_REPO}" --token "${HF_API_TOKEN}"
USER root
RUN cleanup
#
# %runscript
#
USER "${USER_NAME}"
WORKDIR "${HOME}/dev"
SHELL ["/bin/bash", "-c"]
HEALTHCHECK --interval=5m --timeout=30s --start-period=10s --retries=3 \
    CMD ["/bin/bash", "-c", "/healthcheck", "agentic"]
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]