# syntax=docker/dockerfile:1
ARG BASE=bitnami/minideb
ARG TAG=bookworm
ARG IMAGE=$BASE:$TAG
FROM $IMAGE
#
# %labels
#
LABEL author="Jason Wohlgemuth"
LABEL org.opencontainers.image.source=https://github.com/jhwohlgemuth/gold
LABEL org.opencontainers.image.description="Development environment to build on"
LABEL org.opencontainers.image.licenses=MIT
#
# %arguments
#
ARG VERSION=0.0.18
ARG HOME=/root
ARG DEBIAN_FRONTEND=noninteractive
ARG LANG=en_US.UTF-8
ARG LANGUAGE=en_US:en
ARG LC_ALL=en_US.UTF-8
ARG S6_OVERLAY_VERSION=3.1.5.0
ARG S6_OVERLAY_GITHUB=https://github.com/just-containers/s6-overlay
ARG UID=1000
ARG GID=1000
#
# %environment
#
ENV VERSION="${VERSION}"
ENV TZ=America/New_York
ENV SHELL=/usr/bin/zsh
ENV TERM=xterm-256color
ENV PATH="${PATH}:${HOME}/.nix-profile/bin"
ENV PATH="${PATH}:/root/.pixi/bin"
# Used for Pinokio
ENV DISPLAY=:100
ENV GRADIO_SERVER_NAME="0.0.0.0"
#
# %setup
#
# Only supported by Apptainer
# Run setup commands outside of the container (on the host system) after the base image bootstrap.
#
# %files
#
ADD --chmod=0755 ./provision/dev/* /tmp/scripts/
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" /tmp
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-x86_64.tar.xz" /tmp
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz" /tmp
ADD "${S6_OVERLAY_GITHUB}/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz" /tmp
#
# %post
#
SHELL ["/bin/bash", "-c"]
WORKDIR "${HOME}"
RUN ln -snf "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone \
    && /tmp/scripts/install_dependencies.sh \
    && git clone https://github.com/aspiers/stow.git /tmp/stow \
        && cd /tmp/stow \
        && autoreconf --install --force \
        && ./configure \
        && make install clean \
        && cd "${HOME}" \
    && curl -fsSL https://shell.jasonwohlgemuth.com/install.sh | bash \
    && install_dotnet \
    && install_ohmyzsh \
    && install_homebrew \
    && install_nix && nix-env --install --file /tmp/scripts/manifest.nix \
    && /usr/bin/pwsh -Command /tmp/scripts/Install-Modules.ps1 \
    && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" \
        && brew tap jandedobbeleer/oh-my-posh \
        && brew bundle --file /tmp/scripts/Brewfile \
        && brew cleanup --prune=all \
        && eval "$(pkgx integrate)" \
    && /tmp/scripts/configure_locale.sh \
    && /tmp/scripts/configure_ohmyzsh.sh \
    && tar -C / -Jxpf /tmp/s6-overlay-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-x86_64.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-noarch.tar.xz \
    && tar -C / -Jxpf /tmp/s6-overlay-symlinks-arch.tar.xz \
    && addgroup --gid "${GID}" nonroot \
    && adduser --uid "${UID}" --gid "${GID}" --disabled-password --gecos "" nonroot \
    && echo 'nonroot ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && cleanup
#
# %runscript
#
WORKDIR "${HOME}/dev"
HEALTHCHECK NONE
ENTRYPOINT [ "/init" ]
CMD ["/bin/zsh"]