#!/usr/bin/with-contenv bash
# shellcheck shell=bash

/home/linuxbrew/.linuxbrew/bin/llama-server \
    --jinja \
    --ssl-key-file "${HOME}/certs/my.key" \
    --ssl-cert-file "${HOME}/certs/my.pem" >> /etc/services.d/"$1"/log 2>&1