healthCheckTimeout: 500
proxy:
  listen: "http://0.0.0.0:10732"
macros:
  "context_size": "${env.LLAMA_ARG_CTX_SIZE}"
  "parallel": "${env.LLAMA_ARG_N_PARALLEL}"
  "models_dir": "${env.HOME}/models"
  "ssl_key": "${env.HOME}/certs/my.key"
  "ssl_cert": "${env.HOME}/certs/my.pem"
models:
  "gpt-oss-20b":
    proxy: "http://127.0.0.1:${PORT}"
    cmd: |
      llama-server
      --offline
      --batch-size 2048
      --host 0.0.0.0
      --jinja
      --model ${models_dir}/gpt-oss-20b
      --port ${PORT}
      --sleep-idle-seconds 600
      --tools all
      --ubatch-size 2048
  "vllm-coder":
    proxy: "http://127.0.0.1:${PORT}"
    description: "When should the model be used?"
    cmd: |
      podman run
      --name ${MODEL_ID}
      --init
      --rm
      --gpus all
      --publish ${PORT}:8000
      -v "${env.HOME}/models:/root/models"
      docker.io/vllm/vllm-openai:latest
      --model ${models_dir}/Qwen2.5-0.5B-Instruct-Q4_K_M.gguf
      --port 8000
      --serving-name vllm-coder
    cmdStop: podman stop ${MODEL_ID}
    checkEndpoint: "none"
    ttl: 0
