name: 'Build and Push Docker Image'

description: 'Build and push a docker image with a given name'

inputs:
  image-name:
    description: 'Image name'
    required: true
    default: 'dev'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image-name }}